### ISSUE TITLE
Add support for primary condition in hybrid queries

### ISSUE THREAD

**Issue by GianpaoloR** [redis/NRedisStack#135]
Vector similarity KNN queries are in the form <primary_filter_query>=>[<vector_similarity_query>].

It seems that NRedisStack is currently supporting only the basic version, with the wildcard as a precondition, i.e.
`*=>[<vector_similarity_query>]
`

But it is not supporting the primary filter query yet, e.g.
`(@someProperty:someValue)=>[<vector_similarity_query>]`

The above command doesn't fail, but it will always return 0 matches, whatever the primary condition.
Also, looking at the existing search tests, no one is targeting a full hybrid query with a primary condition specified.
Using the `.AddFilter()` to specify the primary filter query doesn't seem to be an option, because it would be applied _after_ the KNN search, which is not the desired behaviour.

**Comment by shacharPash** [comment]
@GianpaoloR, thanks for submitting this issue! 
could you please share a code example?

**Comment by shacharPash** [comment]
Hi, I tried to write code with a hybrid query but the code behaved as expected, I am sending you my code and I would appreciate it if you could tell me what you did differently so that I can understand what the problem is:
```c#
     public void AdvancedQueryOperationsTest()
     {
         ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost");
         IDatabase db = redis.GetDatabase();
         db.Execute("FLUSHALL");
         ISearchCommands ft = db.FT();

         // Vector Similarity Search (VSS)
         // Data load :)
         db.HashSet("vec:1", new HashEntry[]
         {
             new("vector", (new float[] { 1f, 1f, 1f, 1f }).SelectMany(BitConverter.GetBytes).ToArray()),
             new("tag", "A")
         });
         db.HashSet("vec:2", new HashEntry[]
         {
             new("vector", (new float[] { 2f, 2f, 2f, 2f }).SelectMany(BitConverter.GetBytes).ToArray()),
             new("tag", "A")
         });
         db.HashSet("vec:3", new HashEntry[]
         {
             new("vector", (new float[] { 3f, 3f, 3f, 3f }).SelectMany(BitConverter.GetBytes).ToArray()),
             new("tag", "B")
         });
         db.HashSet("vec:4", new HashEntry[]
         {
             new("vector", (new float[] { 4f, 4f, 4f, 4f }).SelectMany(BitConverter.GetBytes).ToArray()),
             new("tag", "A")
         });

        // Index creation:
        try { ft.DropIndex("vss_idx"); } catch { };
        Assert.True(ft.Create("vss_idx", new FTCreateParams().On(IndexDataType.HASH).Prefix("vec:"),
            new Schema()
            .AddTagField("tag")
            .AddVectorField("vector", VectorField.VectorAlgo.FLAT,
                new Dictionary<string, object>()
                {
                    ["TYPE"] = "FLOAT32",
                    ["DIM"] = "4",
                    ["DISTANCE_METRIC"] = "L2"
                }
        )));
        
        // Search:
        float[] vec = new[] { 2f, 3f, 3f, 3f };
        var res = ft.Search("vss_idx",
                    new Query("@name:{A}=>[KNN 2 @vector $query_vec]")
                    .AddParam("query_vec", vec.SelectMany(BitConverter.GetBytes).ToArray())
                    .SetSortBy("__vector_score")
                    .Dialect(2));
```
If I wrote * instead of `@name:{A}`, res should contain vec:2 and vec:3.
but because vec:3 has the tag 'B', he gets filtered and the result is vec:2 and vec:1
