### ISSUE TITLE
Add support for Dev Containers

### ISSUE THREAD

**Issue by haysch** [redis/NRedisStack#165]
# Context

The current NRedisStack setup has a bit of a steep curve to go into for people looking to contribute or hack away.
The test suite depends on, and uses, specific version of `redis-stack`, which require some initial configuration to get started.
Additionally, multiple versions of .NET is required for different test runners.

# Solution

Add support for [Dev Containers](https://containers.dev/) to enable an easy to setup, reproducible development environment.
It is possible to provide a compose list that runs the required Redis instances, as well as require .NET versions for the development container.

# Drawbacks

As I am unaware of how your current development setup is:
* Another development to maintain/support for the current contributors, which might not be worth it in the short, nor long run.

---

Looking forward to discuss the possibility, as it helped me getting started with developing for NRedisStack!

**Comment by shacharPash** [comment]
@haysch Thanks for the feedback!
Dev Containers sounds like a good idea
Do you have experience with it?

**Comment by shacharPash** [comment]
@haysch We can use what you already have as a base and make changes to fit exactly our needs.
What are you saying?

**Comment by haysch** [comment]
Will tidy it a bit up, and then open a PR.

By the way, thanks for an awesome and active library - your work is highly appreciated 👍

**Comment by haysch** [comment]
How do we want to support multiple Redis versions?

The pipeline tests three different versions, but the test suite uses a single `REDIS` env variable or `localhost:6379`, if env variable is not set.

How do you usually do it today?

In my environment I have spinner up the three versions used by the pipeline, and then specify different test tasks that points to the respective Redis instance.

**Comment by shacharPash** [comment]
Locally I test against redis-stack:edge. And the CI also checks the other versions for me.
Sounds like what you offer is better.

**Comment by shacharPash** [comment]
@haysch How's it going? Do you want to send what you have in the meantime and we will continue together?

**Comment by haysch** [comment]
Will have some time in the evening.
Life has been going on 🙂

**Comment by haysch** [comment]
@shacharPash Added an initial commit, but it seems like some tests are failing for v6.2.6 and v7.0.6 - any idea why?

Please let me know what you think, or make any changes as you see fit!

**Comment by shacharPash** [comment]
completed in #169
