### ISSUE TITLE
Unable to search by nested field value

### ISSUE THREAD

**Issue by Mookker** [redis/NRedisStack#166]
Thanks for reporting an issue in NRedisStack! Please update the appropriate text below, as much data as possible really helps!

**NRedisStack Version**: 0.8.0
**Redis Stack Version**: 6.2.6?

**Description**: I'm trying to search by nested field value, but unable find any good examples. 
Sample JSON is
```javascript
{
   "header" : {
     "version":1
     "type": "Type"
   },
     "body" : {
     "description" : "ABC"
   }
}
``` 
So, I am basically going to do something like
```c#
foreach (var doc in ft.Search("idx1", 
             new Query("@Header.Version: (1)")
             ).ToJson())
{
    Console.WriteLine(doc);
}
``` 

Is there any functionality that allows me to do it?

**Comment by haysch** [comment]
Hi there,

Could you show how you create the index?

Also, could you provide the output of `MODULE LIST` (shows enabled modules and version) from redis-cli?

According to the RediSearch documentation it should be doable by indexing the nested field and specify an alias via `AS`.

```
FT.CREATE myIdx ON JSON SCHEMA $.header.version AS version NUMERIC
```
