### ISSUE TITLE
DropIndex does not delete documents (keys) on it

### ISSUE THREAD

**Issue by alexmanie** [redis/NRedisStack#179]
Thanks for reporting an issue in NRedisStack! Please update the appropriate text below, as much data as possible really helps!

**NRedisStack Version**
0.6.1

**Redis Stack Version**
RediSearch 2.6.12

**Description**
DropIndex does not delete keys/documents under it.
Although calling with true or false, the same happens. The index is deleted, but the keys already exists.

I suspect it's related to FT.DROPINDEX functionallity, as if I call if with or without "DD" param from redis-cli, I've got the same results.

Any idea or workaround to delete index keys when dropped?

**Comment by shacharPash** [comment]
Hey @alexmanie :)
In [FT.DROPINDEX](https://redis.io/commands/ft.dropindex/)'s documentation it says: 

> If an index creation is still running ([FT.CREATE](https://redis.io/commands/ft.create) is running asynchronously), only the document hashes that have already been indexed are deleted. The document hashes left to be indexed remain in the database.

  Maybe this is the cause of your problem?
  
  In any case, you are welcome to send a code sample and I will check if the problem occurs for me as well

**Comment by shacharPash** [comment]
@alexmanie Did you manage?
Asking to know whether to close the issue

**Comment by alexmanie** [comment]
Hi @shacharPash , 

The issue can be closed. I figure out how to solve it. Adding the keys using the "index prefix" instead of the "index name", links the keys properly to the indexes.
So, dropping the index now removes all keys (when DD is specified).
