### ISSUE TITLE
Help request: How to wire up NRedisStack in IServiceCollection / ASP.Net Core

### ISSUE THREAD

**Issue by Richard87** [redis/NRedisStack#190]
Thanks for reporting an issue in NRedisStack! Please update the appropriate text below, as much data as possible really helps!

**NRedisStack Version**: 0.9.0
**Redis Stack Version**: 7.0.11

**Description**: 
How is NRedisStack recommended to wire up?

I Would guess `IConnectionMultiplexer` could be set up as a singleton, while `IDatabase` a scoped service?

```cs
builder.Services.AddSingleton(ConnectionMultiplexer.Connect("localhost:6379"));
builder.Services.AddScoped<IDatabase>(opt =>
{
    var con = opt.GetRequiredService<IConnectionMultiplexer>();
    return con.GetDatabase();
});
```

Any advice? :)

**Comment by davidmoseley66** [comment]
Hi
I think you are asking the questing in the wrong place. Your question seems to be about how to connect to redis, wich is covered by [StackExchange documentation](https://stackexchange.github.io/StackExchange.Redis/Basics).

Read section "Basic Usage" and "Using a redis database". 

## Basic Usage
> Note that ConnectionMultiplexer implements IDisposable and can be disposed when no longer required. This is deliberately not showing using statement usage, because it is exceptionally rare that you would want to use a ConnectionMultiplexer briefly, as the idea is to re-use this object.

## Using a redis database
>
The object returned from GetDatabase is a cheap pass-thru object, and does not need to be stored. Note that redis supports multiple

I would continue storing the ConnectionMultiplexer, and the use the `GetDatabase()` whenever i need to use the database

**Comment by Richard87** [comment]
Thanks, I didn't notice that document!
