### ISSUE TITLE
NRedisStack doesn't follow lib-name format used in other clients

### ISSUE THREAD

**Issue by uglide** [redis/NRedisStack#204]
**NRedisStack Version**: What version of the library are you using

**Redis Stack Version**: Any

**Description**: 

When we don't specify `LibraryName` in `GetDatabase` method NRedisStack uses wrong lib-name https://github.com/redis/NRedisStack/blob/master/tests/NRedisStack.Tests/Core%20Commands/CoreTests.cs#L57

**Expected lib-name:**
`NRedisStack(.NET_v{Environment.Version})`

**Actual lib-name:** 
`NRedisStack;.NET-{Environment.Version}`

More on lib-name suffix format https://github.com/redis/redis-doc/pull/2537/files?short_path=11daa65#diff-11daa650b42390d47ba51b9e3dfdf7de0a1521e67b5e213af1f2fafa940d131a

**Comment by shacharPash** [comment]
@uglide  If the user sends LibraryName on their own, what should be the format? 
right now its:
`NRedisStack({LibraryName});.NET-{Environment.Version})`

**Comment by uglide** [comment]
@shacharPash It should be:

```
NRedisStack({LibraryName};.NET_v{Environment.Version})
```

In other words, we treat runtime information in the same way as user-defined library name.
