### ISSUE TITLE
Create C# code snippets for bitfields

### ISSUE THREAD

**Issue by sav-norem** [redis/NRedisStack#209]
The redis.io webpage for [bitfields](https://redis.io/docs/data-types/bitfields/) needs the C# example as well. The python equivalent can be used to copy the setup and can be found [here](https://github.com/redis/redis-py/pull/3002/files#diff-75621ec51da32e7f657243e238496703618ccfb882d0eac5b7c61ed400e1830f)

The first line of the file needs to be the ID for the example - # EXAMPLE: bitfield_tutorial

Each separate section is delimited with a tag that you will need to copy exactly for it to appear in the correct place, ie.
```
# STEP_START bf
{code}                                    
# STEP_END

# HIDE_START, # HIDE_END, # REMOVE_START, and # REMOVE_END can be used for debugging and deleting keys. Hide will hide until a user expands the example, remove will only be seen in the source code and will never appear on the webpage.
```

Examples should live in [this folder ](https://github.com/redis/NRedisStack/tree/master/tests/Doc)

@dwdougherty and I will be reviewing and tracking these issues - feel free to tag us with any questions

**Comment by atakavci** [comment]
support for BITFIELD command is not built in to the SE.Redis and for obvious reasons it will not be implemented in NRedisStack. We will come back to this topic if we have it supported in the future.
