### ISSUE TITLE
Add clarification about the features provided by this package

### ISSUE THREAD

**Issue by YagoBiermann** [redis/NRedisStack#243]
Currently, there is no information about the features provided by this package. Why/When should I use this instead of the vanilla StackExchange.Redis? What problem does it solve? I believe that this information is valuable enough to be included in the documentation.

**Comment by chayim** [comment]
Have you seen [this part](https://github.com/redis/NRedisStack/#note) of the README.  What else might be helpful @YagoBiermann

**Comment by shacharPash** [comment]
hey @YagoBiermann, do you have more questions or can this issue be closed?
In general, what NRedisStack provides is support for Redis Stack commands (Search, Json, Bloom, TimrSeries etc.) in addition to the Redis Core commands implemented in StackExchange.Redis
You can find more information about RedisStack [here](https://redis.io/docs/about/about-stack/).

**Comment by YagoBiermann** [comment]
Sorry for the delay, I was confused because I mistakenly thought that StackExchange.Redis already offered support for the Redis stack. This issue can be closed, Thank you for your time.
