### ISSUE TITLE
TestJsonTransaction seems to fail arbitrarily

### ISSUE THREAD

**Issue by atakavci** [redis/NRedisStack#289]
it failed in the test ([TestJsonTransaction](https://github.com/redis/NRedisStack/actions/runs/8655556758/job/23734681775#step:12:252)) due to `System.NotSupportedException : Nested batches are not supported`
while it runs successfully for most of executions.

**Comment by shacharPash** [comment]
@atakavci this issue fixed in PR #290? can I close as completed?
and next time You can write "Closes/Fixes #289" instead "fixes the issue #289" and that would close the issue when the PR merges

**Comment by atakavci** [comment]
it is fixed now. i'll keep that in mind to add the phrase, thanks.
