### ISSUE TITLE
Index.Attribute throws error for sortable fields

### ISSUE THREAD

**Issue by ivanjt-srai** [redis/NRedisStack#291]
**NRedisStack Version**: 0.12.0
**Redis Stack Version**: 
![image](https://github.com/redis/NRedisStack/assets/131339942/c3e1659f-382c-492f-b3e8-8546d60ecfe9)

**Description**: 
For sorted attributes , index.Attributes throws  _request.System.IndexOutOfRangeException: Index was outside the bounds of the array._
![image](https://github.com/redis/NRedisStack/assets/131339942/b572ff97-b647-42a0-8f7f-34796e587a99)

This is how i add text field: 
                            schema.AddTextField(item.Key, sortable: true);

This is how index is created 

var ftCreateParams = new FTCreateParams().On(IndexDataType.HASH)
                                        .Temporary(expiryTime)
                                        .Prefix(payloadPrefix);

note that , almost all of the fields are marked as sortable

**This issue does not happen when i mark the fields false for sortable.**

Please help !

**Comment by shacharPash** [comment]
Hi @ivanjt-srai , I'm on it 👍

**Comment by shacharPash** [comment]
@ivanjt-srai [this PR](https://github.com/redis/NRedisStack/pull/295) should solve it, LMK what you think.

**Comment by ivanjt-srai** [comment]
sure @shacharPash , when can I expect the fix to be available to use?

**Comment by shacharPash** [comment]
@ivanjt-srai In the next few days we will merge it to master

**Comment by ivanjt-srai** [comment]
do we have any update on this @shacharPash ?

**Comment by shacharPash** [comment]
> do we have any update on this @shacharPash ?

@atakavci

**Comment by uglide** [comment]
@ivanjt-srai The fix has been merged into the main branch.
