### ISSUE TITLE
FT.Aggregate with APPLY - text fields data is returing in lowercase if we do the multi column sort 

### ISSUE THREAD

**Issue by balasahebr92** [redis/NRedisStack#296]
Thanks for reporting an issue in NRedisStack! Please update the appropriate text below, as much data as possible really helps!

**NRedisStack Version**:0.12.0

**Redis Stack Version**: 

**Description**: 
I am facing the issue with multi column sort - the text fields data am getting in lowercase, i need this values what i stored. the values will be stored as in capital / pascalcase / camelcase but all values am getting in the lowercase. I have did some observation on this please look into this

**FT.Aggreagate & FT.Search Commands**
**FT.Search** -  
Its support the single column sorting 
If I have decimal fields & its type as numeric with set sortable true then,  sorting for this column not doing perfect. 
Example - _**FT.Search indexname "*" SORTBY sales_ty ASC;**_
FT.Search command not support for multi column sorting
       
**2. FT.AGGREGATE with LOAD** 
Its support the multi column sort for text & numeric fields is working as expected 
but if I have the field like (sales - 23435.3446 ) in that case its not working as expected 
Example - _**FT.AGGREGATE indexname * LOAD * SORTBY 6 @manufacturer_desc DESC @units_ty DESC @sortassist DESC LIMIT 0 40;**_
 
**3.  FT.AGGREGATE with APPLY**
Its support the multi column sort for text & numeric fields is working as expected. 
For numeric field like (2364 or 3435.345), its also working as expected 
But issue is for string/text sortable fields - where its return the data in lowercase
Example - **_FT.AGGREGATE indexname * SORTBY 6 @manufacturer_desc DESC @units_ty DESC @sortassist DESC APPLY @manufacturer_id AS manufacturer_id APPLY @manufacturer_desc AS manufacturer_desc APPLY @week_id AS week_id APPLY   @week_enddate AS week_enddate APPLY @units_ly AS units_ly APPLY @fiscal_week_desc AS fiscal_week_desc APPLY @units_ty AS units_ty APPLY @sortassist AS sortassist LIMIT 0 40_**

**Stored Result**

![image](https://github.com/redis/NRedisStack/assets/131889053/f346938c-acb9-43c2-9ef3-a726889937d8)

**Sorting Result**

![image](https://github.com/redis/NRedisStack/assets/131889053/326fc393-fb65-476c-b261-4a170d8811fd)

Please help on this ASAP

**Comment by balasahebr92** [comment]
Hi slorello89, thanks for help!

If I use this command ( FT.AGGREGATE test * SORTBY 2 @name ASC LOAD * ) by taking LOAD after the sortby its looks good up to page no 3 but after for page no 4, 5, 6 its returning the previous page records. am taking **load *** becuase for payload, properties are dyanamically created for every scehma.

**Examples - scenarion 1**
1) FT.AGGREGATE test * SORTBY 2 @name ASC LOAD * limit 1 10  -  page 1 => looks good
2) FT.AGGREGATE test * SORTBY 2 @name ASC LOAD * limit 11 10 - page 2 => looks good
3) FT.AGGREGATE test * SORTBY 2 @name ASC LOAD * limit 21 10 - page 3 => looks good
4) FT.AGGREGATE test * SORTBY 2 @name ASC LOAD * limit 31 10 - page 4 => looks good
5) FT.AGGREGATE test * SORTBY 2 @name ASC LOAD * limit 41 10 - page 5 => returning the page 4 records 
5) FT.AGGREGATE test * SORTBY 2 @name ASC LOAD * limit 51 10 - page 6 => returning the page 4 records 

**Examples - scenarion 2**
FT.AGGREGATE dev1481pl_36aedac5cd0e4f0d777499bff2bc812ef8ad4f6854ac4fc490c710ddcccdee33 *  SORTBY 4 @textFields DESC @sortassist ASC LOAD 6 text1 text2 numeric1 numeric2 text 3 numeric4 LIMIT 1 10

for this example - its showing the correct records but the text fields showing in lowercase again.

Please help on this.

**Comment by slorello89** [comment]
Hi @balasahebr92 - I'm not able to reproduce either of these issues on my end. Not scenario 1 where you get duplicate pages, not scenario 2 where the UNF does not seem to apply.

For scenario 1, I'd ensure that the index is in the state you think it is before querying it.

For scenario 2 my shot in the dark guess is that you did not drop and recreate the index between runs 

I created a [gist](https://gist.github.com/slorello89/70799dce320d88f3a1e15bcf82300d6d) with some example code so you can see what I'm talking about (this uses UNF and works).

**Comment by balasahebr92** [comment]
Hi slorello89, thanks for help!

Still am not clear the thing 
With this below query its working fine for me but as per your suggestion need to use the loadAll after the sortby 
FT.AGGREGATE indexname* LOAD * SORTBY 4 @column1 ASC @column2 DESC LIMIT 1 10

Example - lets I have the 100K+ records and I need to retrieve the data by page size 10 every time but sometime like ( 20, 50, 100 pagesize) so what type of query you suggest for best performance point of view

**Query 1**

FT.AGGREGATE indexname* LOAD * SORTBY 4 @column1 DESC @column2 DESC  LIMIT 1 10

**Query 2**
FT.AGGREGATE indexname* LOAD 7 column1 column2 column3 column4 column5 SORTBY 4 @column1 DESC @column2 DESC  LIMIT 1 10

**Query 3**
FT.AGGREGATE indexname* SORTBY 4 @column1 DESC @column2 DESC  LOAD *  LIMIT 1 10

**Query 4**

FT.AGGREGATE indexname*  SORTBY 4  @column1 DESC @column2 DESC LOAD 7 column1 column2 column3 column4 column5  LIMIT 1 10

**Comment by balasahebr92** [comment]
Hi slorello89 

As per above scenarios am using the **Query 2** it's working for me as per my expectation but if I use the load after the **SORTBY** - for text fields its return the data in lowercase even if I declare this text column as UNF while creating the index. 

thank you very much!

**Comment by slorello89** [comment]
Hi @balasahebr92 - as I mentioned, you need to use the `LOAD` first to override the normalization. RE create the index with UNF, are you certain that you actually deleted the index first? Otherwise  it will not override what's already in the schema.

**Comment by balasahebr92** [comment]
Hi [slorello89](https://github.com/slorello89) 
Yeah, its looks good now. 

thanks for help. am closing this issue now from my side
