### ISSUE TITLE
Add support for IBatch.JSON()

### ISSUE THREAD

**Issue by R0boC0p** [redis/NRedisStack#297]
Hi, just a little suggestion:

**NRedisStack Version**:  0.12.0

**Description**:  I am currently batching operations, and want to use the JSON commands.
As you know there is an extension method already:

```c#
public static JsonCommands JSON(this IDatabase db)
{
    return new JsonCommands(db);
}
```

If we would change it to 

```c#
public static JsonCommands JSON(this IDatabaseAsync db)
{
    return new JsonCommands(db);
}

// this 
var batch = Redis.CreateBatch();
var redisJson = new JsonCommandsAsync(batch);

// could be
var redisJson = Redis.CreateBatch().JSON();
```

Maybe it's worth adding.
Many Thanks

**Comment by shacharPash** [comment]
Hey @R0boC0p, did you see the [Pipeline](https://github.com/redis/NRedisStack/blob/e913dfc2be17e225bd8224c7bcf186fed871ede1/src/NRedisStack/Pipeline.cs#L5) support?
Its NRedisStack wrapper for IBatch

here some examples:
https://github.com/redis/NRedisStack/blob/e913dfc2be17e225bd8224c7bcf186fed871ede1/Examples/PipelineExample.md
https://github.com/redis/NRedisStack/blob/e913dfc2be17e225bd8224c7bcf186fed871ede1/Examples/PipelineWithAsync.md
