### ISSUE TITLE
TimeSeries Create function always creates the TS as "uncompressed" when specifying true or false to the function argument

### ISSUE THREAD

**Issue by Auttcast** [redis/NRedisStack#319]
**NRedisStack Version**: 0.12.0

**Description**:

Expected:
I'm calling the TS create function with the **uncompressed** argument set to false, expecting that it should create the TS with compression enabled.

Actual:
The TS is still created as uncompressed.

Notes:
In debugging with redis MONITOR I can see that specifying true or false still issues a TS.CREATE with the UNCOMPRESSED parameter set.

It looks like the problem is with this function in TimeSeriesParamsBuilder where it is setting the UNCOMPRESSED option entirely based on the presence of the arg regardless of it's value.
https://github.com/redis/NRedisStack/blob/master/src/NRedisStack/TimeSeries/TimeSeriesParamsBuilder.cs#L109

Workaround:
Set the **uncompressed** argument to **null**

**Comment by uglide** [comment]
Hello @Auttcast 

Thanks for the bug report. We will address it soon.
