### ISSUE TITLE
Exception utilising NRedisStack.Search.DataTypes.InfoResult with MissingIndex or EmptyIndex

### ISSUE THREAD

**Issue by SudoZachCampbell** [redis/NRedisStack#351]
**NRedisStack Version**: 1.13.1
**Redis Stack Version**: 7.4

**Description**: 
It looks like INDEXMISSING and INDEXEMPTY are required in `NRedisStack.Search.DataTypes.InfoResult.booleanAttributes`, currently the `GetRedisResultDictionaryArray` function is failing with an Index out of Bounds exception

**Comment by atakavci** [comment]
hi @SudoZachCampbell , 
thank you for using NRedisStack and letting us know about the case you are having.

i am planning to work on this next week.
It would be nice if you can provide the relevant code snippet to reproduce to issue, it will boost the speed on our side, 
thanks..
