### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array. at NRedisStack.Search.Document.Load

### ISSUE THREAD

**Issue by ruwentos** [redis/NRedisStack#352]
**NRedisStack Version**: 0.13.0

**Redis Stack Version**: 2.8.16

**Description**: We got an 'Index was outside the bounds of the array' exception at NRedisStack.Search.Document.Load. This happend while we searched Redis with a query through `SearchCommandsAsync.SearchAsync(string indexName, Query q)`.

I can test the static function `NRedisStack.Search.Document.Load` and will get this exception every time the parameter `RedisValue[]? fields` contains an uneven count of items.
So first I thought this would be a flaw in your code. But then I wrote a test that mimics the situation where the exception occurred and I'm not able to reproduce this exception.
What I see is that your code depends on what comes out of `await _db.ExecuteAsync(SearchCommandBuilder.Search(indexName, q))` in your `SearchCommandsAsync` function:
```
public async Task<SearchResult> SearchAsync(string indexName, Query q)
{
    if (q.dialect == null && defaultDialect != null)
    {
        q.Dialect((int)defaultDialect);
    }

    return (await _db.ExecuteAsync(SearchCommandBuilder.Search(indexName, q))).ToSearchResult(q);
}
```
My questions:
1. Have you ever experienced/heard about that the `RedisResult` object was shaped so that your code through an exception?
2. Can you think of a cause of this?
3. Do you consider to change your code that it could handle the situation without an exception?

kind regards

Swen

**Comment by chaimtevel** [comment]
Hi,

I'm having a similar situation. I haven't verified this 100% but as per [the docs](https://redis.io/docs/latest/commands/ft.search/#:~:text=If%20a%20relevant%20key%20expires,the%20total%20number%20of%20results.) the results can include missing documents if a ttl is set in some scenarios.

**Comment by chaimtevel** [comment]
I spent a bit of time debugging and the exception is occurring [here](https://github.com/redis/NRedisStack/blob/master/src/NRedisStack/Search/Document.cs#L43).

In my scenario the `fields` only has a single empty element (which I think is due to have that null value mentioned in the redis docs) causing this line to throw this exception:

```cs
ret[fieldName] = fields[i + 1];
```

**Comment by atakavci** [comment]
hey @ruwentos @chaimtevel,

i understand this exception shows up arbitrarily and we don't have the exact steps to reproduce it, is that correct ?

**Comment by chaimtevel** [comment]
For me it was not occurring regularly, but when it does happen it happens fairly consistently till the bad data clears out.

If I recall correctly the return data that was causing this was something along these lines:

Command:
```
FT.Search resident_queue_idx * FILTER didSuccessfullyProcess 0 0 FILTER queueType 1 1 FILTER attempts 0 10 SORTBY requestTimestamp DESC LIMIT 0 3 DIALECT 3
```

Results:
```
1) "228"
2) "queue_name:prefix-name-167036"
3) 1) null
```

If I can replicate then I'll post what the data actually looked like.

Thanks!

**Comment by atakavci** [comment]
hey @chaimtevel , i built a test case(below) to experiment on the behaviour.
looks like we got it in the aggregated exceptions in `searchTask.Exception`

let me work on it a bit more to tailor the right behavior in `Load`; this needs to be handled and search result should be handed over to the caller BUT!!.. but either we need a proper way to say something is wrong with this individual doc or we need to trim it from results. Not exactly sure TBH. May be we should check what other libraries do..

```c#
    [Fact]
    public void TestDocumentLoad_Issue352()
    {
        IDatabase db = redisFixture.Redis.GetDatabase();
        db.Execute("FLUSHALL");
        var ft = db.FT();

        Schema sc = new Schema().AddTextField("first", 1.0).AddTextField("last", 1.0).AddNumericField("age");
        Assert.True(ft.Create(index, FTCreateParams.CreateParams(), sc));

        db.HashSet("student:1111", new HashEntry[] { new("first", "Joe"), new("last", "Dod"), new("age", 18) });

        Assert.True(db.KeyExpire("student:1111", TimeSpan.FromMilliseconds(500)));

        Boolean cancelled = false;
        Task searchTask = Task.Run(() =>
        {
            for (int i = 0; i < 100000; i++)
            {
                SearchResult result = ft.Search(index, new Query());
                if (cancelled) break;
            }
        });
        Task.WhenAny(searchTask, Task.Delay(2000)).GetAwaiter().GetResult();

        Assert.Null(searchTask.Exception);
        cancelled = true;
    }
```
