### ISSUE TITLE
Documentation Tracker

### ISSUE THREAD

**Issue by chayim** [redis/NRedisStack#66]
As part of a great first experience, let's add an examples folder, so that we can help users better use it!

- [x] #60 
- [x] #61 
- [x] #62 
- [x] #63  
- [x] #64 
- [x] #65

**Comment by Jeevananthan-23** [comment]
Hi @chayim, I would like to work on these examples.

**Comment by chayim** [comment]
@Jeevananthan-23 that's awesome! Anything in paritcular... @shacharPash feel free to work with @Jeevananthan-23

**Comment by shacharPash** [comment]
hey

> Hi @chayim, I would like to work on these examples.

Hi @Jeevananthan-23 
I added an option for pipelines in this PR: #50 
This is a test I did that illustrates how to use the pipelines:
```csharp
    [Fact]
    public async Task TestJsonPipeline()
    {
        var pipeline = new Pipeline(ConnectionMultiplexer.Connect("localhost"));
        pipeline.Db.ExecuteAsync("FLUSHALL");

        string jsonPerson = JsonSerializer.Serialize(new Person { Name = "Shachar", Age = 23 });
        var setResponse = pipeline.Json.SetAsync("key", "$", jsonPerson);
        var getResponse = pipeline.Json.GetAsync("key");

        pipeline.Execute();

        Assert.Equal("True", setResponse.Result.ToString());
        Assert.Equal("{\"Name\":\"Shachar\",\"Age\":23}", getResponse.Result.ToString());
    }
```
If you could make an example of using pipelines that would be great.
Thank you!

**Comment by Jeevananthan-23** [comment]
Sure will work on it! 👍

**Comment by Jeevananthan-23** [comment]
> hey
> 
> > Hi @chayim, I would like to work on these examples.
> 
> Hi @Jeevananthan-23 I added an pipeline support in this PR: #50 This is a test I did that illustrates how to use the pipelines:
> 
> ```cs
>     [Fact]
>     public async Task TestJsonPipeline()
>     {
>         var pipeline = new Pipeline(ConnectionMultiplexer.Connect("localhost"));
>         pipeline.Db.ExecuteAsync("FLUSHALL");
> 
>         string jsonPerson = JsonSerializer.Serialize(new Person { Name = "Shachar", Age = 23 });
>         var setResponse = pipeline.Json.SetAsync("key", "$", jsonPerson);
>         var getResponse = pipeline.Json.GetAsync("key");
> 
>         pipeline.Execute();
> 
>         Assert.Equal("True", setResponse.Result.ToString());
>         Assert.Equal("{\"Name\":\"Shachar\",\"Age\":23}", getResponse.Result.ToString());
>     }
> ```
> 
> If you could make an example that does not include what I added for the test (FLUSHALL, Asserts, etc.) and maybe make a more complex example that combines commands from several modules.
> 
> Thank you!

@shacharPash could you please sync the examples branch with master it helps me to add examples without any conflict 
and #50 merged recently. 😊

Thanks!

**Comment by shacharPash** [comment]
> > hey
> > > Hi @chayim, I would like to work on these examples.
> > 
> > 
> > Hi @Jeevananthan-23 I added an pipeline support in this PR: #50 This is a test I did that illustrates how to use the pipelines:
> > ```cs
> >     [Fact]
> >     public async Task TestJsonPipeline()
> >     {
> >         var pipeline = new Pipeline(ConnectionMultiplexer.Connect("localhost"));
> >         pipeline.Db.ExecuteAsync("FLUSHALL");
> > 
> >         string jsonPerson = JsonSerializer.Serialize(new Person { Name = "Shachar", Age = 23 });
> >         var setResponse = pipeline.Json.SetAsync("key", "$", jsonPerson);
> >         var getResponse = pipeline.Json.GetAsync("key");
> > 
> >         pipeline.Execute();
> > 
> >         Assert.Equal("True", setResponse.Result.ToString());
> >         Assert.Equal("{\"Name\":\"Shachar\",\"Age\":23}", getResponse.Result.ToString());
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you could make an example that does not include what I added for the test (FLUSHALL, Asserts, etc.) and maybe make a more complex example that combines commands from several modules.
> > Thank you!
> 
> @shacharPash could you please sync the examples branch with master it helps me to add examples without any conflict and #50 merged recently. 😊
> 
> Thanks!

Done

**Comment by Jeevananthan-23** [comment]
hello @shacharPash, #75 was created for examples take a look at it and provide your feedback. Any idea how to add `Transaction`
examples? I think no separate API not created yet for the Transaction. 🙂
