### ISSUE TITLE
Wrong arguments count in VectorField

### ISSUE THREAD

**Issue by MatteoMilanese** [redis/NRedisStack#70]
When creating a new vector field through [`Schema.AddVectorField`](https://github.com/redis/NRedisStack/blob/master/src/NRedisStack/Search/Schema.cs#L388) the generated command has a wrong number of parameters.

Example:
```c#
var schema = new Schema().AddVectorField("fieldTest", Schema.VectorField.VectorAlgo.HNSW, new Dictionary<string, object>()
{
    ["TYPE"] = "FLOAT32",
    ["DIM"] = "128",
    ["DISTANCE_METRIC"] = "COSINE"
});
```

which generates the following:
```text
FT.CREATE test SCHEMA fieldTest VECTOR HNSW 3 TYPE FLOAT32 DIM 128 DISTANCE_METRIC COSINE
```
and it should be
```text
FT.CREATE test SCHEMA fieldTest VECTOR HNSW 6 TYPE FLOAT32 DIM 128 DISTANCE_METRIC COSINE
```

The error in the code is at [this line](https://github.com/redis/NRedisStack/blob/master/src/NRedisStack/Search/Schema.cs#L226) which only takes into account dictionary's keys while should consider also values (i.e.: `Attributes.Count()` should be doubled).

**Comment by shacharPash** [comment]
Hey @MatteoMilanese , 
Thanks, that’s indeed an issue.
I'll fix it 👍
