### ISSUE TITLE
Implement Transaction for Redis Stack Commands

### ISSUE THREAD

**Issue by shacharPash** [redis/NRedisStack#78]
similar to pipelines (#50).
with `MULTI` and `EXEC`.

**Comment by Jeevananthan-23** [comment]
```cs
 public class Transactions
    {
        public Transactions(IConnectionMultiplexer muxer)
        {
            _transaction = muxer.GetDatabase().CreateTransaction();
        }

        public Transactions(IDatabase db)
        {
            _transaction = db.CreateTransaction();
        }

        private ITransaction _transaction;

        public void AddCondition(Condition condition)
        {
            _transaction.AddCondition(condition);
        }

        public void Execute()
        {
            _transaction.Execute();
        }

        public void ExecuteAsync()
        {
            _transaction.ExecuteAsync();
        }
    }
  ```
  @shacharPash does this helps?

**Comment by shacharPash** [comment]
Yes 👍 
Do you want to send it as a PR or will I take it?
We need to add tests and maybe some more changes to support all the modules.

**Comment by Jeevananthan-23** [comment]
I'll work on the PR.

**Comment by shacharPash** [comment]
> I'll work on the PR.
> 
> > Yes 👍 Do you want to send it as a PR or will I take it? We need to add tests and maybe some more changes to support all the modules.
> 
> Do modules support only `Async`?

Any command has Sync and Async version.
for example:
`Json.Set` - Sync
`Json.SetAsync` - Async

When you use Pipelines or Transaction, you only has access to the *async* methods - because the result of
each operation will not be known until after `Execute` (or `ExecuteAsync`) has completed.

**Comment by Jeevananthan-23** [comment]
@shacharPash  #79 was created for drafted one transaction support and should add some more tests

**Comment by Jeevananthan-23** [comment]
`Condition` class does not support any redis modules 
 ```cs
[Fact]
    public void TransactionExample()
    {
        var tran = new Transactions(ConnectionMultiplexer.Connect("localhost"));

        tran.AddCondition(Condition.HashNotExists("profesor:5555", "first")); // Condition class 
        tran.Db.HashSetAsync("profesor:5555", new HashEntry[] { new("first", "Albert"), new("last", "Blue"), new("age", "55") });
        var condition = tran.ExecuteAsync();
        Assert.True(condition.Result);
    }
```
